---
title: "Gráficos em ggplot part.2"
author: "Yuri"
format: html

execute: 
  freeze: auto
  cache: true
  warning: false
---

## Meu Segundo Plot

Importando dados:

```{r}
## Para importar uma planilha em xlsx
library(tidyverse)
library(readxl)
mg <- read_excel("dados-diversos.xlsx")
```

Visualizar:

```{r}
## Para visualizar pontos 
mg |> 
  ggplot(aes(trat, comp))+
  geom_point()
```

Para visualizar pontos ***sem sobreposição:***

```{r}
mg |> 
  ggplot(aes(trat, comp))+
  geom_boxplot(aes())+
  geom_jitter(width = 0.1)

## Para retirar o valor duplo de outlier, pontos iguais na extremidade do gráfico

p_box <- mg |> 
  ggplot(aes(trat, comp))+
  geom_boxplot(outlier.color = NA,
               fill = "orange",
               size = 0.3,
               width = 0.4)+
  geom_jitter(width = 0.1,
              height = 0,
              size = 2,
              color = "black")+
   scale_y_continuous(limits = c(5,20),
                     n.breaks = 10)+
  labs(y= "Lesion size (mm)",
  x="")+
  theme_bw()
ggsave("figs/plot2.png", bg = "white")
```

Gráficos de barras com ***desvio padrão:***

```{r}
##preparando para fazer grafico de barras
p_means <- mg |> 
  group_by(trat) |> 
  summarise (comp_mean = mean(comp),
             comp_sd = sd(comp)) |> 
  ggplot(aes(trat, comp_mean))+
  #geom_col(fill =" orange",
   #        width = 0.5)+
  geom_point()+
    scale_y_continuous(limits = c(7,18),
                     n.breaks = 6)+
  geom_errorbar(aes(ymin = comp_mean - comp_sd , ymax = comp_mean + comp_sd,
                    width = 0.05))
ggsave("figs/mean_sd.png",
       width = 4,
       height = 4,
       bg ="white")
p_box
p_means
```

Composição do plot:

```{r}
library(patchwork)
p_box + p_means
(p_box | p_means)+
  plot_annotation(tag_levels = "A",
                  title = "Gráficos que impressionam")
ggsave("figs/combinado.png")
p_box / p_means
(p_box | p_means)/
  (p_box)
```

Gráficos (dados-diversos):

```{r}
survey <- read_xlsx("dados-diversos.xlsx", 
                    sheet = "survey")
survey |> 
  filter(state== "RS") |>
  count(species) |> 
  ggplot(aes(species, n))+
  geom_col(width = 0.4, fill = "steelblue")+
  coord_flip()+
labs(x = "", y = "Number of Isolates")+
  theme_bw()
ggsave("figs/barplot.png", bg ="white")

```
