---
title: "Blocos e Parcelas Subdivididas"
author: "Yuri"
format: html

execute: 
  freeze: auto
  cache: true
  warning: false
---

### Blocos Casualizados

```{r}
library(readxl)
library(tidyverse)

fungicidas <- 
  read_excel("dados-diversos.xlsx", "fungicida_campo")
```

Modelos anova com bloco:

```{r}
aov_fung <- aov(sev~trat + rep, data = fungicidas)
summary(aov_fung)

```

Verificar as premissas e estimar os valores médios:

```{r}
library(performance)
library(DHARMa)
check_normality(aov_fung)
check_heteroscedasticity(aov_fung)
#plot(simulateResiduals(aov_fung))

library(emmeans)
means_fung <- emmeans(aov_fung, ~trat)
library(multcomp)
library(multcompView)

cld(means_fung)

plot(means_fung)+
  coord_flip()+
  theme_minimal()
```

Parcelas subdividida (splitoplot):

```{r}
milho <- read_excel("dados-diversos.xlsx", "milho")
##Base R
#dbc
#
aov_milho_bloco <- aov(index ~ factor(block) + hybrid*method + 
                              Error(factor(block)/hybrid/method), data = milho)
summary(aov_milho_bloco)
```

```{r}
library(car)
library(lme4)
milho$block <- as.factor(milho$block)
mix2 <- lmer (index~block + hybrid*method +
                (1|block/hybrid), data = milho)
anova(mix2)
check_normality(mix2)
check_heteroscedasticity(mix2)
```

*Corrigido:*

```{r}
library(lme4)
# using blocks
milho$block <- as.factor(milho$block)
mix2 <- lmer(sqrt(index) ~ block + hybrid*method + (1|block/hybrid), data = milho)
library(car)
Anova(mix2)
check_normality(mix2)
check_heteroscedasticity(mix2)
means_mix2 <- emmeans(mix2, ~ hybrid | method)
means_mix2
cld(means_mix2)
```
