---
title: "Importação de Dados"
author: "Yuri"
format: html

execute: 
  freeze: auto
  cache: true
  warning: false
---

## Importando Dados DE:

Pacotes:

```{r}
cars
cars2 <- cars
cars2$speed
speed <- cars2$speed
speed
```

***DATAFRAME*** de um pacotes:

```{r}
library(r4pde)
RustSoybean
df <- RustSoybean
```

Documento ***Excel***:

```{r}
library(readxl)
magnesio <- read_excel("dados-diversos.xlsx")
escala <- read_excel("dados-diversos.xlsx", "escala")
```

Documento ***CSV***:

```{r}
# using read . and _ csv
library(tidyverse)
read.csv("dados-diversos.csv")
magnesio2 <- read_csv("dados-diversos.csv")
magnesio3 <- read.csv("dados-diversos.csv")

# using read.table
magnesio4 <-
read.table("dados-diversos.txt", header = TRUE)
```

*Google **sheet**:*

```{r}
library(gsheet)
magnesio5 <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1aID5Dh6PlBVCKzU1j7k-WA6zuWQWE2NhtWEgdJtt5iA/edit?usp=sharing")
survey <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1aID5Dh6PlBVCKzU1j7k-WA6zuWQWE2NhtWEgdJtt5iA/edit#gid=366054269")

fusarium <- read_csv("https://raw.githubusercontent.com/emdelponte/epidemiology-R/main/data/fusarium_banana.csv")
fusarium
```
