---
title: "Anvo 2 Fator"
author: "Yuri"
format: html

execute: 
  freeze: auto
  cache: true
  warning: false
---

Carregando pacotes:

```{r}
library(tidyverse)
library(readxl)
```

Abrindo conjunto em fatorial: milho:

```{r}
data <-read_excel("dados-diversos.xlsx", "fungicida_vaso")
data2 <- data|> 
  mutate(inc = dis_sp / n_sp * 100)

data2 |> 
  ggplot(aes(x = treat, y= inc))+
  geom_jitter()+
  facet_wrap(~dose)
```

Modelo de anova 2 fatores qualitativos:

```{r}
ml1 <- aov(log(inc+0.5) ~treat*dose,
           data = data2)
summary(ml1)

##libary perfomace premissas

library(performance)
check_normality(ml1)
check_heteroscedasticity(ml1)
library(DHARMa)
plot(simulateResiduals(ml1))


##estimar medias para cada tratamento
library(multcompView)
library(multcomp)
library(emmeans)
means_ml <- emmeans(ml1, ~ treat|dose, 
                    type = "responses")
means_ml


cld(means_ml)

library(agricolae)
cv.model(ml1)
```

Fatorial 3 fatores:

```{r}

milho <- read_excel("dados-diversos.xlsx","armazena")

milho2 <- milho |>
  filter(tempo==8)

milho2 |> 
  ggplot(aes(factor(tipo), peso_mil,
             color = factor(umidade)))+
  geom_jitter(width = 0.1)+
  facet_wrap(~umidade)
## testar interção entre tipo de armazenamento e umidade

m2 <- aov(peso_mil ~ factor(tipo)*factor(umidade),
          data = milho2)
summary(m2)
```

Quando não possui significancia entre a interação, testar as variáveis independentes.

```{r}
milho3 <- read_excel("dados-diversos.xlsx", 
                    "milho")

m4 <- aov(yield ~ hybrid,
          data = milho3)
summary(m4)
check_heteroscedasticity(m4)
plot(simulateResiduals(m4))
medias_m4 <- emmeans(m4, ~ hybrid)
medias_m4
#Tuckey
cld(medias_m4)
pwpm(medias_m4)
pwpp(medias_m4)
```
